/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentation.mainui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.skin.AutumnSkin;
import org.jvnet.substance.skin.SubstanceSaharaLookAndFeel;
import org.jvnet.substance.theme.SubstanceOliveTheme;
import org.jvnet.substance.watermark.SubstanceBubblesWatermark;

import presentation.tools.OutputHelper;
import presentation.tools.ViewReplyMessage;
import vo.studentvo.StudentInfoVO;
import businesslogic.managerbl.Manager;
import businesslogic.studentbl.StudentInfo;
import businesslogic.teacherbl.Teacher;

/**
 *
 * @author LiuWT-ASUS
 */
public class LoginUI extends JFrame implements ViewReplyMessage{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	OutputHelper helper=new OutputHelper();
    /**
     * Creates new form LoginUI
     */
	static {
		try{
			try{
				UIManager.setLookAndFeel(new SubstanceLookAndFeel());
				
					
			}catch(UnsupportedLookAndFeelException  ex){
				System.out.println(ex.getMessage());
			}
		}catch(Exception et){
				System.out.println(et.getMessage());
		}
		SubstanceSaharaLookAndFeel.setSkin(new AutumnSkin());
		SubstanceLookAndFeel.setCurrentWatermark(new SubstanceBubblesWatermark());
		//		SubstanceLookAndFeel.setCurrentTitlePainter(new Glass3DDecorationPainter());
		
	//	SubstanceLookAndFeel.setCurrentTheme(new SubstanceLightAquaTheme());

		SubstanceLookAndFeel.setCurrentTheme(new SubstanceOliveTheme());  
		  
	     //  SubstanceLookAndFeel.setCurrentTheme(new SubstanceJadeForestTheme());  
	};
    public LoginUI() {
    	
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usertype = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        key = new javax.swing.JPasswordField();
        loginbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        usertype.setModel(new javax.swing.DefaultComboBoxModel<String>
        	(new String[] { "学生", "任课教师", "院系教务老师", "教务处老师" }));

        jLabel1.setText("身份：");

        jLabel2.setText("帐号：");

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        jLabel3.setText("密码：");

        loginbutton.setText("登录");
        loginbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbuttonMouseClicked(evt);
            }
        });
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        jLabel4.setText("NJWUCourseSystem V 1.0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(key)
                            .addComponent(id)
                            .addComponent(usertype, 0, 130, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usertype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void loginbuttonMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        int type = usertype.getSelectedIndex();
        String userid = id.getText();
    	char[] password = key.getPassword();
    	String pass = "";
    	for(int i=0 ; i <password.length ; i++){
    		pass+=password[i];
    	}
    	boolean valid = false;
    	int login=0;//登陆验证类型：0 用户不存在，1 密码错误，2 成功
        switch(type){       
        case 0 :
        	//学生部分
        	StudentInfoVO siv = new StudentInfoVO();
        	siv.setID(userid);
        	siv.setKey(password);
        	valid = new StudentInfo().isKeyValid(siv);
        	if(valid){
        		new StudentMainUI().createFrame(userid);
        		this.setVisible(false);
        	}else{
        		JOptionPane.showMessageDialog(null, "Wrong PassWord !");
        	}
        	break;
        case 1:
        	//任课教师
        	Teacher teacher = new Teacher(userid , pass);
        	if(teacher.isVaild()){
        		teacher.initTeacher();
        		new TeacherMainUI(teacher);
        	}else{
        		JOptionPane.showMessageDialog(null, "Wrong PassWord !");
        	}
        	break;
        case 2:
        	//院系教务老师
        	login=new Manager().login(userid, pass); 
        	if(login==0){
        		helper.outputToDialog(ID_NOT_EXIST);
        	}else if(login==1){
        		helper.outputToDialog(PW_ERROR);
        	}else{        	
        		new FacultyMainFrame(userid).start();
        		this.dispose();        	
        	}
        	break;
        case 3:
        	//教务处老师
        	login=new Manager().login(userid, pass); 
        	if(login==0){
        		helper.outputToDialog(ID_NOT_EXIST);
        	}else if(login==1){
        		helper.outputToDialog(PW_ERROR);
        	}else{        	
        		new DeanMainUI(userid);
        	}       		
        	break;
        	
        }
    }                                        

    private void idActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField key;
    private javax.swing.JButton loginbutton;
	private javax.swing.JComboBox<String> usertype;
    // End of variables declaration                   
}
